packages:
  - design-tokens
  - mobile
  - doctor-portal
  - website

allowBuilds:
  esbuild: false
  msgpackr-extract: false
  sharp: false
  workerd: false

ignoredBuiltDependencies:
  - esbuild
  - sharp
